# Generated by Django 4.1.6 on 2023-03-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='a',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='b',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='c',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='d',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
