# Generated by Django 4.1.6 on 2023-03-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_agent_a_agent_b_agent_c_agent_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posn', models.IntegerField()),
            ],
        ),
    ]
