# Generated by Django 4.1.6 on 2023-03-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='level1_pos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='level2_pos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='level3_pos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='level4_pos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='level5_pos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='level6_pos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='level7_pos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='level8_pos',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
