# Generated by Django 4.1.7 on 2023-03-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0005_alter_position_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='level_count',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
